Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -34,12 +34,24 @@ jobs:
       timeout-minutes: 15
 
     - name: Get JaCoCo Coverage
-      id: coverage  
+      id: coverage
       run: |
-        coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv) 
+        # Exécute le script de couverture et capture le résultat
+        coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv)
+        
+        # Affiche la couverture pour vérification
+        echo "Extracted coverage: $coverage"
+
+        # Vérifie si la couverture est vide ou invalide
+        if [ -z "$coverage" ] || ! [[ "$coverage" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
+          echo "Error: Coverage is not a valid number."
+          exit 1
+        fi
+
+        # Enregistre la couverture dans les variables d'environnement
         echo "COVERAGE=$coverage" >> $GITHUB_ENV
 
-    - name: Fail if coverage has not improved.
+    - name: Fail if coverage has not improved
       run: |
         coverage=$COVERAGE
         threshold=24.46
@@ -52,7 +64,7 @@ jobs:
 
     - name: Upload Coverage Report
       if: always()
-      uses: actions/upload-artifact@v3
+      uses: actions/upload-artifact@v2
       with:
         name: "Coverage Report - Flags ${{ matrix.flags }}"
         path: target/site/jacoco
