Update test.yml
test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -34,12 +34,20 @@ jobs:
       timeout-minutes: 15
 
     - name: Get JaCoCo Coverage
-      id: coverage  
+      id: coverage
       run: |
+        echo "Calculating coverage for flags: ${{ matrix.flags }}"
         coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv) 
+        
+        # Validate coverage and ensure the value is correct
+        if [ -z "$coverage" ] || ! [[ "$coverage" =~ ^[0-9]+([.][0-9]+)?$ ]]; then
+          echo "Error: Invalid coverage value: $coverage"
+          exit 1
+        fi
+        
         echo "COVERAGE=$coverage" >> $GITHUB_ENV
 
-    - name: Fail if coverage has not improved.
+    - name: Fail if coverage has not improved
       run: |
         coverage=$COVERAGE
         threshold=24.46
@@ -48,6 +56,7 @@ jobs:
           exit 1
         else
           echo "New coverage: $coverage%. Coverage is improved!"
+        fi
 
     - name: Upload Coverage Report
       if: always()
